name: Build and Publish

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - '.github/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: build-and-publish-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # setup Docker buld action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Login to Docker Hardened Images
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@ee4ca427a2f43b6a16632044ca514c076267da23 # v6.19.0
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            strayingfromthepath/ludex:latest
          # build on feature branches, push only on main branch
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          no-cache: true

      - name: Image digest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ steps.docker_build.outputs.digest }}"
